import numpy as np

def fibonacci_sphere(N, R):
    """
    Generate approximately uniform point samples on a sphere using
    the Fibonacci (golden-angle) method.

    Parameters
    ----------
    N : int
        Number of points to generate on the sphere.
    R : array_like or float
        Radius scaling applied to each coordinate. If array-like of shape (3,),
        scaling is anisotropic along each axis; if scalar, scaling is isotropic.

    Returns
    -------
    coords : ndarray of shape (N, 3)
        Cartesian coordinates of the sampled points, multiplied by ``R``.
        Points lie on a sphere generated by the Fibonacci spiral construction.

    Notes
    -----
    The algorithm uses the golden angle ``phi = π(3 − √5)`` to distribute
    points quasi-uniformly. The internal construction sets ``y = r*sin(theta)``
    and assigns ``z = y`` exactly as defined in this function before scaling.
    Centering is not performed; shift by adding a center vector externally.
    """
    # shift to center if needed by adding a center vector afterward
    i = np.arange(N)
    phi = np.pi * (3. - np.sqrt(5.))         # golden angle
    y = 1 - (2*i + 1)/N                      # y = cos(theta)
    r = np.sqrt(1 - y*y)
    theta = i * phi

    x = r * np.cos(theta)
    y = r * np.sin(theta)
    z = y

    coords = np.column_stack((x,y,z))

    return np.multiply(coords, R)